version: "3.8"

services:
  dkron-server:
    image: dkron/dkron:v3.0.6
    ports:
      - "8080"
      - "8946"
      - "6868"
    command: agent --server --retry-join=dkron-server:8946 --bootstrap-expect=2
  dkron-agent:
    image: dkron/dkron:v3.0.6
    ports:
      - "8946"
      - "6868"
    environment:
      - GODEBUG=netdns=go
    command: agent --retry-join=dkron-server:8946 --log-level=debug --tag my_role=executor
